In [41]:
import pandas as pd
import numpy as np

In [42]:
df08 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2008")
df09 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2009")
df10 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2010")
df11 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2011")
df12 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2012")
df13 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2013")
df14 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2014")
df15 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2015")
df16 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2016")
df17 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2017")
df18 = pd.read_excel(r"Raw Data 10yrs_v3.xlsx", sheet_name="2018")

df = [df08,df09,df10,df11,df12,df13,df14,df15,df16,df17,df18]

In [43]:
# Rename columns

for i in range(11):
    currDf = df[i]
    currDf.rename(columns={"Unnamed: 0": "Name", "Unnamed: 1": "Team", "Unnamed: 2": "Pos", "Unnamed: 3": "Age", "Games": "G", "Games.1": "GS", "Passing": "P_Cmp", "Passing.1": "P_Att", "Passing.2": "P_Yds", "Passing.3": "P_TD", "Passing.4": "P_Int", "Rushing": "Ru_Att", "Rushing.1": "Ru_Yds", "Rushing.2": "Y/A", "Rushing.3": "R_TD", "Receiving": "Tgt", "Receiving.1": "Rec", "Receiving.2": "Re_Yds", "Receiving.3": "Y/R", "Receiving.4": "Re_TD", "Fantasy": "Total_Pts", "Fantasy.1": "PPR", "Fantasy.2": "PosRank"}, inplace=True)
    df[i] = currDf.drop(currDf.index[0])
    
df[0]

,Name,Team,Pos,Age,G,GS,P_Cmp,P_Att,P_Yds,P_TD,...,Y/A,R_TD,Tgt,Rec,Re_Yds,Y/R,Re_TD,Total_Pts,PPR,PosRank
1,Drew Brees,NOR,QB,29,16,16,413,635,5069,34,...,-0.05,0,0,0,0,NaN,0,305,305,1
2,Aaron Rodgers,GNB,QB,25,16,16,341,536,4038,28,...,3.7,4,0,0,0,NaN,0,296,296,2
3,Philip Rivers,SDG,QB,27,16,16,312,478,4009,34,...,2.71,0,0,0,0,NaN,0,287,287,3
4,DeAngelo Williams,CAR,RB,25,16,16,0,0,0,0,...,5.55,18,30,22,121,5.5,2,286,308,1
5,Jay Cutler,DEN,QB,25,16,16,384,616,4526,25,...,3.51,2,0,0,0,NaN,0,281,281,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,George Wilson,BUF,NaN,27,16,3,0,0,0,0,...,NaN,0,0,0,0,NaN,0,NaN,NaN,184
575,Kris Wilson,SDG,NaN,27,3,0,0,0,0,0,...,NaN,0,NaN,0,0,NaN,0,NaN,NaN,106
576,D'Juan Woods,JAX,NaN,24,1,0,0,0,0,0,...,NaN,0,NaN,0,0,NaN,0,NaN,NaN,205
577,Wallace Wright,NYJ,NaN,24,16,0,0,0,0,0,...,NaN,0,0,0,0,NaN,0,NaN,NaN,191
578,Joe Zelenka,JAX,NaN,32,16,0,0,0,0,0,...,NaN,0,NaN,0,0,NaN,0,NaN,NaN,102

In [ ]:
# possibly remove players with no position
# should we remove players who have no stats next season?

In [44]:
# add column of next season to current season

for i in range(10):
    currDf = df[i]
    nextDf = df[i+1][["Name", "Total_Pts"]]
    nextDf.rename(columns={"Total_Pts": "Next_Season_Pts"}, inplace=True)
    newDf = pd.merge(currDf, nextDf, how="outer", on=["Name"])
    df[i] = newDf

C:\Users\bucke\mainAnaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [45]:
# remove players who didn't play a game (this is a result of the join)

for i in range(10):
    currDf = df[i]
    for index, row in currDf.iterrows():        
        if isinstance(row["G"], int)==False:
            
            currDf = currDf.drop( axis=0, index=index)
            
    df[i] = currDf  
    
df[3]

,Name,Team,Pos,Age,G,GS,P_Cmp,P_Att,P_Yds,P_TD,...,R_TD,Tgt,Rec,Re_Yds,Y/R,Re_TD,Total_Pts,PPR,PosRank,Next_Season_Pts
0,Aaron Rodgers,GNB,QB,28,15,15,343,502,4643,45,...,3,0,0,0,NaN,0,399,399,1,344
1,Drew Brees,NOR,QB,32,16,16,468,657,5476,46,...,1,0,0,0,NaN,0,396,396,2,346
2,Cam Newton,CAR,QB,22,16,16,310,517,4051,21,...,14,1,1,27,27,0,375,376,3,323
3,Tom Brady,NWE,QB,34,16,16,401,611,5235,39,...,3,0,0,0,NaN,0,370,370,4,340
4,Matthew Stafford,DET,QB,23,16,16,421,663,5038,41,...,0,0,0,0,NaN,0,347,347,5,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,Roberto Wallace,MIA,NaN,25,2,0,0,0,0,0,...,0,NaN,0,0,NaN,0,NaN,NaN,211,NaN
581,Stephen Williams,ARI,NaN,25,2,0,0,0,0,0,...,0,NaN,0,0,NaN,0,NaN,NaN,190,NaN
582,Kris Wilson,BAL,NaN,30,15,0,0,0,0,0,...,0,0,0,0,NaN,0,NaN,NaN,108,NaN
583,Will Yeatman,MIA,NaN,23,3,2,0,0,0,0,...,0,1,0,0,NaN,0,NaN,NaN,100,NaN
584,Joe Zelenka,ATL,NaN,35,16,0,0,0,0,0,...,0,NaN,0,0,NaN,0,NaN,NaN,106,NaN

In [46]:
# export the data
export df

SyntaxError: invalid syntax (Temp/ipykernel_7008/4034114435.py, line 2)